#!/bin/bash

. "${0%/*}/pkgbuild_introspection.inc.sh"

if [[ -f $1 ]]; then
  srcinfo_write_from_pkgbuild "$1"
else
  srcinfo_write_from_pkgbuild "${ABSROOT:-/var/abs}/$1/PKGBUILD"
fi

# vim: set et ts=2 sw=2:
