#!/bin/bash

shopt -s extglob

array_build() {
  # maybe this should handle sparse arrays?
  eval "$1=(\"\${$2[@]}\")"
}

array_eq() {
  local i left right

  array_build 'left' "$1"
  array_build 'right' "$2"

  (( ${#left[*]} == ${#right[*]} )) || return 1

  for (( i = 0; i < ${#left[*]}; ++i )); do
    if [[ ${left[@]:i:1} != ${right[@]:i:1} ]]; then
      return 1
    fi
  done

  return 0
}

funcgrep() {
  { declare -f "$1" || declare -f package; } 2>/dev/null | grep -E "$2"
}

extract_global_var() {
  # $1: variable name
  # $2: multivalued
  # $3: name of output var

  local attr=$1 isarray=$2 outputvar=$3

  if (( isarray )); then
    declare -n ref=$attr
    [[ ${ref[@]} ]] && array_build "$outputvar" "$attr"
  else
    [[ -v $attr ]] && printf -v "$outputvar" %s "${!attr}"
  fi
}

extract_function_var() {
  # $1: function name
  # $2: variable name
  # $3: multivalued
  # $4: name of output var

  local funcname=$1 attr=$2 isarray=$3 outputvar=$4 attr_regex= decl= r=1

  if (( isarray )); then
    printf -v attr_regex '^[[:space:]]*(declare( -[[:alpha:]])*)? %q\+?=\(' "$2"
  else
    printf -v attr_regex '^[[:space:]]*(declare( -[[:alpha:]])*)? %q\+?=[^(]' "$2"
  fi

  while read -r; do
    # strip leading whitespace and any usage of declare
    decl=${REPLY##*([[:space:]])?(declare +(-+([[:alpha:]]) ))}
    eval "${decl/#$attr/$outputvar}"

    # entering this loop at all means we found a match, so notify the caller.
    r=0
  done < <(funcgrep "$funcname" "$attr_regex")

  return $r
}

pkgbuild_get_attribute() {
  # $1: package name
  # $2: attribute name
  # $3: name of output var
  # $4: multivalued

  printf -v "$3" %s ''

  if [[ $1 ]]; then
    extract_global_var "$2" "$4" "$3"
    extract_function_var "package_$1" "$2" "$4" "$3"
  else
    extract_global_var "$2" "$4" "$3"
  fi
}

srcinfo_write_header() {
  printf '%s = %s\n' "$1" "$2"
}

srcinfo_end_section() {
  echo
}

srcinfo_write_attr() {
  # $1: architecture (empty string for arch-independent metadata)
  # $2: attr name
  # $3: attr values

  local arch=$1 attrname=$2 attrvalues=("${@:3}")

  # normalize whitespace, strip leading and trailing
  attrvalues=("${attrvalues[@]//+([[:space:]])/ }")
  attrvalues=("${attrvalues[@]#[[:space:]]}")
  attrvalues=("${attrvalues[@]%[[:space:]]}")

  printf "\t$attrname${arch:+@}$arch = %s\n" "${attrvalues[@]}"
}

pkgbuild_extract_to_srcinfo() {
  # $1: pkgname
  # $2: architecute (empty string for arch-independent metadata)
  # $3: attr name
  # $4: multivalued

  local pkgname=$1 architecture=$2 attrname=$3 isarray=$4 outvalue=

  if pkgbuild_get_attribute "$pkgname" "$attrname" 'outvalue' "$4"; then
    srcinfo_write_attr "$architecture" "$attrname" "${outvalue[@]}"
  fi
}

srcinfo_create_global() {
  srcinfo_write_header 'pkgbase' "${pkgbase:-$pkgname}"

  local singlevalued=(pkgdesc pkgver pkgrel epoch url install changelog)
  local multivalued=(arch groups license checkdepends makedepends depends optdepends
                     provides conflicts replaces source noextract options backup)

  for attr in "${singlevalued[@]}"; do
    pkgbuild_extract_to_srcinfo '' '' "$attr" 0
  done

  for attr in "${multivalued[@]}"; do
    pkgbuild_extract_to_srcinfo '' '' "$attr" 1
  done

  srcinfo_end_section
}

srcinfo_create_package() {
  local pkg=$1 attr= a=

  srcinfo_write_header 'pkgname' "$pkg"

  # single-valued attributes
  for attr in pkgver pkgrel epoch pkgdesc url; do
    pkgbuild_extract_to_srcinfo "$pkg" '' "$attr" 0
  done

  # multi-valued attributes
  for attr in backup license groups; do
    pkgbuild_extract_to_srcinfo "$pkg" '' "$attr" 1
  done

  # FIXME: these attribute should be architecture specific
  for attr in depends optdepends provides conflicts replaces; do
    pkgbuild_extract_to_srcinfo "$pkg" '' "$attr" 1
  done

  srcinfo_end_section
}

srcinfo_create() {
  local pkg

  srcinfo_create_global

  for pkg in "${pkgname[@]}"; do
    srcinfo_create_package "$pkg"
  done
}

clear_environment() {
  # optimized for small exclusion lists.
  mapfile -t environ < <(compgen -A variable | grep -xvF "$(printf '%s\n' "$@")")

  # expect that some variables marked read only will complain here
  unset -v "${environ[@]}" 2>/dev/null
}

srcinfo_create_from_pkgbuild() {
  (
    clear_environment PATH

    shopt -u extglob
    . "$1" || exit 1
    shopt -s extglob
    srcinfo_create
  )
}

# vim: set et ts=2 sw=2:
